### ISSUE TITLE
Error [ShardingReadyDied]: Shard 0's process exited before its Client became ready.

### ISSUE THREAD

**Issue by UnknownX0001** [CorwinDev/Discord-Bot#103]
help?

![image](https://user-images.githubusercontent.com/88265081/218154791-4eb3b4ac-266c-44fd-a110-c6f97045fda3.png)

**Comment by CryptoLover705** [comment]
@UnknownX0001 Make sure your using atleast node v17.0.0 or you will see this error

**Comment by UnknownX0001** [comment]
> @UnknownX0001 Make sure your using atleast node v17.0.0 or you will see this error

hey @CryptoLover705 I am using node v17.9.1 and still getting this error what do I do?

**Comment by CryptoLover705** [comment]
I would try resetting your bots token and see if that helps @UnknownX0001

**Comment by UnknownX0001** [comment]
> I would try resetting your bots token and see if that helps @UnknownX0001

i will try. also, i forgot one important information, the code works locally but doesnt when i host it with any host (i.e. replit or paid hosts)

**Comment by CryptoLover705** [comment]
Ahh, sounds like replit/paid hosts node version are not working properly, I have tried it both locally and via a VPS and they worked fine

**Comment by TharunRalph** [comment]
@UnknownX0001 Check Out #faq in Discord Server Just Try "kill 1" In Shell It Will Solve Your Problem

**Comment by UnknownX0001** [comment]
> @UnknownX0001 Check Out #faq in Discord Server Just Try "kill 1" In Shell It Will Solve Your Problem

i had tried that before, it does not work

**Comment by UnknownX0001** [comment]
> Ahh, sounds like replit/paid hosts node version are not working properly, I have tried it both locally and via a VPS and they worked fine

i even tried with discloud, but even that showed the error

**Comment by CryptoLover705** [comment]
@UnknownX0001 If you want, reach out to me on discord, I would be more then happy to help you try & fix this issue

`CryptoLover#6396` my discord name

**Comment by UnknownX0001** [comment]
@CryptoLover705 hey thanks for that, fortunately my friend had forked the same exact code which i did from replit (corwin bot's code on replit) and i forked it from him, it seems working now.
