### ISSUE TITLE
Some commands error!

### ISSUE THREAD

**Issue by MATHEROS5DEV** [CorwinDev/Discord-Bot#113]
Sometimes there are some commands which take like 40 mins and just say thinking and after that it give error application did not respond!

**Comment by DotwoodMedia** [comment]
Do you have examples of commands? And what errors do you get?

**Comment by MATHEROS5DEV** [comment]
Yes like messages rules command or images wallpaper

**Comment by Ruben-Schadron** [comment]
message rules command is because you need to be a developer. In the other case I don't know
