### ISSUE TITLE
Lavalink Issue

### ISSUE THREAD

**Issue by HusseinAhmed2** [CorwinDev/Discord-Bot#139]
When I change the lavalink to any another link I get this error:
ERROR >> Node lavalink.techpoint.world had an error: Unexpected op "ready" with data: [object Object]

When I keep it the same as default, This happen:
Bot >> Started on 6 servers!
System >> Lavalink connected!
System >> Lavalink connected!
System >> Lavalink connected!
System >> Lavalink connected!
System >> Lavalink connected!
ERROR >> Node lava.link had an error: Unable to connect after 5 attempts.

**Comment by Mythic-Frost** [comment]
same

**Comment by CorwinDev** [comment]
Hi,

please use our lavalink.techpoint.world, and the error then popping up isn’t anything to matter!

so just use our lavalink:
Host: lavalink.techpoint.world
Port: 80
Password: techpoint

**Comment by HusseinAhmed2** [comment]
Just music-trivia iguess

**Comment by HusseinAhmed2** [comment]
> Hi,
> 
> please use our lavalink.techpoint.world, and the error then popping up isn’t anything to matter!
> 
> so just use our lavalink: Host: lavalink.techpoint.world Port: 80 Password: techpoint

just games music-trivia ig
