### ISSUE TITLE
chatbot not answering without a error ig?

### ISSUE THREAD

**Issue by asnalino** [CorwinDev/Discord-Bot#140]
Hello my chatbot dont answer me 
idk if this error is it but here this is what i get

![image](https://user-images.githubusercontent.com/123818929/230705829-66bbccb8-68a5-41a7-a1c4-5c02f3d0ec36.png)

how can i fix

**Comment by AtomicGaming666** [comment]
that error is nothing inportent be sure that you have an Open AI api key setup in your .env file if you do have a key and its not working then idk just remove the key and use the backup chatbot that in the code that sould just work with no keys

**Comment by AsnaCode** [comment]
i got the key and the backups bot cannot multiple languages so no sorry xd
