### ISSUE TITLE
RangeError: No avaiable nodes

### ISSUE THREAD

**Issue by mabyewwwwww** [CorwinDev/Discord-Bot#149]
this happens every time i ues the /music play command
![image](https://user-images.githubusercontent.com/130321849/233732602-eed0f767-19fb-4f42-82d4-d2f8f730575f.png)

**Comment by Hardik7547** [comment]
Same issue

**Comment by CorwinDev** [comment]
Hi,

please use our lavalink.techpoint.world
Host: lavalink.techpoint.world
Port: 80
Password: techpoint
