### ISSUE TITLE
about adding new commands

### ISSUE THREAD

**Issue by SvarbusZodis** [CorwinDev/Discord-Bot#159]
Hello, i added a new command same as announcement  just a different name and now i get this error
![image](https://user-images.githubusercontent.com/72148172/236649902-ddc5d9ad-38e0-4621-bf75-87bba71b11fe.png)

**Comment by Ruben-Schadron** [comment]
Join [our server](https://discod.gg/XuaHWdbbsM). There we can help you better and faster.
