### ISSUE TITLE
Lavalink error

### ISSUE THREAD

**Issue by SensiblePoet256** [CorwinDev/Discord-Bot#161]
 npm run start

> discordbot@10.0.0 start
> node . --trace-warnings

Database >> MongoDB is connecting...

Bot >> Started on 1 servers!
System >> Lavalink connected!
System >> Lavalink connected!
System >> Lavalink connected!
System >> Lavalink connected!
System >> Lavalink connected!
ERROR >> Node lava.link had an error: Unable to connect after 5 attempts.

**Comment by FlexKleks** [comment]
If you run the bot on Windows, make sure you have JDK 16.0.2 installed. You also need the Lavalink.jar (https://github.com/freyacodes/Lavalink/releases/tag/3.4) and an application.yml (https://github.com/freyacodes/Lavalink/blob/master/LavalinkServer/application.yml.example).

Start the JAR with the command `java -jar Lavalink.jar` and correct the Lavalink data in the .env file. For example, host `127.0.0.1` and port `2333`. Make sure that the password in both files matches.

**Comment by Ruben-Schadron** [comment]
Join [our server](https://discod.gg/XuaHWdbbsM). There we can help you better and faster. We also posted there a new lavalink
