### ISSUE TITLE
Lavalink Error 

### ISSUE THREAD

**Issue by pxsx** [CorwinDev/Discord-Bot#165]
ERROR >> Node Frankfurt-node.hosting-network.eu had an error: Unexpected op "ready" with data: [object Object]

Somebody knows how to fix that ?

**Comment by pxsx** [comment]
i also installed ffmpeg-static buts its not working

**Comment by Ruben-Schadron** [comment]
That is more a warning. You can choose to skip that error or change to an other package

**Comment by pxsx** [comment]
But the Music Feature wont work if i skip the error
Otherwise which package can i use to fix that issue ?
