### ISSUE TITLE
lavalink connect to wrong port. 

### ISSUE THREAD

**Issue by 0x7da** [CorwinDev/Discord-Bot#182]
i use the port 2333 & Lavalink deosnt changed it

ERROR >> Node astrada-lavalink had an error: connect ECONNREFUSED 192.168.16.2:443
^C^CUnhandled promise rejection: MongooseError: Operation `developers.findOne()` buffering timed out after 10000ms
    at Timeout.<anonymous> (/usr/src/app/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:175:23)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)

**Comment by PHV08** [comment]
use another lavalink host lmao

**Comment by Skipsqueak514** [comment]
> use another lavalink host lmao

nothings funny stop making a mockery of people and look at yourself in the mirror

**Comment by CorwinDev** [comment]
It is just like @PHV08 said, just use ours or another lavalink.
