### ISSUE TITLE
can't change file name

### ISSUE THREAD

**Issue by LIKEaBORZ** [CorwinDev/Discord-Bot#183]
(rename .env.example to .env) Replit!

**Comment by Fujitime** [comment]
You can use the Secrets feature in Replit to store confidential environment variables. Follow these steps:

1. Open your project in Replit.
2. Click the 'Lock' icon in the left panel.
3. Add a new environment variable using the 'New Secret' button.
4. Provide a name and value for the variable.
5. Access the environment variable in your code using `process.env.VARIABLE_NAME`.

Refer to the [Replit documentation ](https://docs.replit.com/programming-ide/workspace-features/secrets) for more information.

**Comment by LIKEaBORZ** [comment]
i have a new problem![https://cdn.discordapp.com/attachments/1111001900624650270/1126602939453161673/333333333333333333333333333.png](url)

**Comment by Fujitime** [comment]
"Have you run the 'npm install' command in a previous shell?"

**Comment by bless3dd** [comment]
> "Have you run the 'npm install' command in a previous shell?"

not working
