### ISSUE TITLE
Chat bot not working? Here is the solution!

### ISSUE THREAD

**Issue by nightmarefoxy397** [CorwinDev/Discord-Bot#197]
It seems that OpenAI is having some problems with API keys as they are very limited.

CorwinDev offers an alternative which is their own AI (https://coreware.nl/) and here I will show you how to use it!

![image](https://github.com/CorwinDev/Discord-Bot/assets/143332799/a6e7d108-b32e-4ba7-8b4c-a58266dab50c)

Go to /Discord-bot/src/events/message/messageCreate.js and remove from line 231 - 257

Also delete line 259, 284, 285. And that's it! You are now running the Chat Bot using CorwinDev AI.

After making the above changes the code should look like this:

![image](https://github.com/CorwinDev/Discord-Bot/assets/143332799/2221e20b-94f9-4820-8af7-40e6fdd4cd57)

(Remove console.log(json); but in your case it is not necessary, I just did it for convenience)

**Comment by CorwinDev** [comment]
You just don't set the OPENAI .env variable and you don't have to do this stuff
