### ISSUE TITLE
Lava.link error

### ISSUE THREAD

**Issue by Murat1Na** [CorwinDev/Discord-Bot#199]
ERROR >> Node lava.link had an error: Unable to connect after 5 attempts.

**Comment by KofySpace** [comment]
Erela.js is simply unmaintained

**Comment by CorwinDev** [comment]
That does not mean lavalink shouldn't work

If it still doesn’t work try our lavalink.
host : lavalink.techpoint.world
port : 80
password: techpoint

**Comment by KofySpace** [comment]
Look at this repo, you will be able to see the maintained libraries : https://github.com/lavalink-devs/Lavalink#client-libraries

**Comment by CorwinDev** [comment]
> This is what is currently configured in my config, but not functional

What doesn't function?

**Comment by CorwinDev** [comment]
And what library is the best in your opinion?

**Comment by KofySpace** [comment]
> And what library is the best in your opinion?

Moonlink could be pretty good

**Comment by KofySpace** [comment]
> > This is what is currently configured in my config, but not functional
> 
> What doesn't function?

Since the erela.js library is no longer maintained, nothing works. You will simply have to use another maintained library

**Comment by CorwinDev** [comment]
> > > This is what is currently configured in my config, but not functional
> > 
> > 
> > What doesn't function?
> 
> Since the erela.js library is no longer maintained, nothing works. You will simply have to use another maintained library

Not maintained !== not working

But i agree we should move to another library

**Comment by KofySpace** [comment]
> > > > This is what is currently configured in my config, but not functional
> > > 
> > > 
> > > What doesn't function?
> > 
> > 
> > Since the erela.js library is no longer maintained, nothing works. You will simply have to use another maintained library
> 
> Not maintained !== not working
> 
> But i agree we should move to another library

Yup
