### ISSUE TITLE
Lavalink unexpected response: 200

### ISSUE THREAD

**Issue by Its-Krzysztof** [CorwinDev/Discord-Bot#236]
What I tried: Setting lavalink to lavalink.techpoint.world
I tried using my own lavalink aswell.
![image](https://github.com/CorwinDev/Discord-Bot/assets/77639981/6ddc444e-5665-4ea2-a396-bee0a0036d62)
![image](https://github.com/CorwinDev/Discord-Bot/assets/77639981/c90fe439-7761-4e8d-a61a-63d3777b5962)

**Comment by Its-Krzysztof** [comment]
SOlved.

**Comment by LND694** [comment]
how did you solved it? I am looking for a lavalink server credentials which are actually working
