### ISSUE TITLE
Issue:

### ISSUE THREAD

**Issue by MrShadowDev** [CorwinDev/Discord-Bot#32]
Help fixing please: 
![image](https://user-images.githubusercontent.com/71973368/206736304-58b56a2e-9ba5-450d-b3e2-438c7c253d41.png)

**Comment by CorwinDev** [comment]
You need to filll in the webhook file correctly.
Example: 
Webhook: https://discord.com/api/webhooks/1050693980842639390/Ldx_PF6pZRBOMW15TLdIHFYtvLPzbPeUonViXFtgYIMKcjxHKjdhS-cdqAabcedqTklSx

ID: 1050693980842639390
Token: Ldx_PF6pZRBOMW15TLdIHFYtvLPzbPeUonViXFtgYIMKcjxHKjdhS-cdqAabcedqTklSx

**Comment by MrShadowDev** [comment]
What token should i put then?

**Comment by MrShadowDev** [comment]
Can you make installation steps in readme file? Thx

**Comment by MrShadowDev** [comment]
![image](https://user-images.githubusercontent.com/71973368/206745418-c1f055ab-593e-434a-9554-8e476cad5308.png)

**Comment by MrShadowDev** [comment]
Its not working sir!
![image](https://user-images.githubusercontent.com/71973368/206745841-ef7a02ea-4ab0-44e9-80fc-2435c13a309a.png)
Bot is off!
![image](https://user-images.githubusercontent.com/71973368/206745919-5ff65568-a664-42cd-ac6e-e4cd1ba96326.png)

**Comment by CorwinDev** [comment]
https://discord.gg/qHXxpQKC2H Can you join me discord? So i can get in more detail

**Comment by MrShadowDev** [comment]
Sure!

**Comment by BasToTheMax** [comment]
sus
