### ISSUE TITLE
data.FLAGS.includes("DEVELOPER")

### ISSUE THREAD

**Issue by JordanC28** [CorwinDev/Discord-Bot#5]
To execute some commands it asks me to be a developer, how do I assign myself as a developer of the bot?

**Comment by CorwinDev** [comment]
Log into your mongodb, go to collections. find table badges insert data:
add this
![image](https://user-images.githubusercontent.com/88144943/195005294-385017a8-8254-4a50-8fec-d9e0662902d6.png)
Replace the numbers with your own discord id
