### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Andriusyes** [CorwinDev/Discord-Bot#56]
When you use /invites leaderboard showing error same with levels leaderboard
![Screenshot_2022-12-18-15-40-10-925-edit_com discord](https://user-images.githubusercontent.com/67488665/208301564-3729d093-c6ec-4406-8e42-c416d3b0b943.jpg)
![Screenshot_2022-12-18-15-39-59-577-edit_com discord](https://user-images.githubusercontent.com/67488665/208301570-5525af76-e9d2-49d9-b611-84ad2ded56cc.jpg)

**Comment by Ruben-Schadron** [comment]
It is probably a bug in the source. It don't display the error always so we don't really know where the issue is.
