### ISSUE TITLE
Can't start the bot

### ISSUE THREAD

**Issue by FuryCraft** [CorwinDev/Discord-Bot#57]
Hi I have this error when I run the bot
![image](https://user-images.githubusercontent.com/44116544/208650294-08f9d67a-b8d7-4d66-b07f-0f3c3c8cc29d.png)

**Comment by CorwinDev** [comment]
`kill 1` run that in terminal/shell

**Comment by FuryCraft** [comment]
Thanks

**Comment by CorwinDev** [comment]
> Thanks

##### [Join our discord for fastest support](https://discord.gg/qHXxpQKC2H)
