### ISSUE TITLE
Where to Specify the Owner ID of the Bot Owner ?

### ISSUE THREAD

**Issue by Pasi-dev-xyz** [CorwinDev/Discord-Bot#58]
Hello 
Where do i specify the owner id of the bot to use the developers commands because i get everytime this error when using command that starts with /developers ( Only Bot developers are allowed to do this) <--- The Error
i searched in the database and in the files from the bot but i didnt found something

**Comment by CorwinDev** [comment]
You could run this command: npm run add-dev <your discord id> 
Replace the <your discord id> with your discord id

**Comment by Pasi-dev-xyz** [comment]
okay thx
