### ISSUE TITLE
Don't know where to use "npm add-dev"

### ISSUE THREAD

**Issue by TheForgottenOne5982** [CorwinDev/Discord-Bot#69]
Am I need to paste to replit shell or mongo db? If I need to paste in mongo db where to past @CorwinDev  pls help!

**Comment by CorwinDev** [comment]
Paste it in shell

**Comment by CorwinDev** [comment]
replit

**Comment by CorwinDev** [comment]
https://discord.gg/jVeC7cFX5T join our discord where we can provide better support
