### ISSUE TITLE
bot stuck on "2 events of warn loaded"

### ISSUE THREAD

**Issue by creeperita09** [CorwinDev/Discord-Bot#85]
title says it all
console log:
 npm run start

> discordbot@10.0.0 start
> node . --trace-warnings

Database >> MongoDB is connecting...
System >> Loading commands ...

System >> 42 commands of Command loaded
System >> 5 commands of ContextMenu loaded

System >> Loading events ...

System >> 5 events of channel loaded
System >> 7 events of client loaded
System >> 3 events of emoji loaded
System >> 3 events of event loaded
System >> 4 events of giveaway loaded
System >> 11 events of guild loaded
System >> 3 events of invite loaded
System >> 5 events of message loaded
System >> 6 events of music loaded
System >> 5 events of role loaded
System >> 14 events of stats loaded
System >> 3 events of sticker loaded
System >> 3 events of thread loaded
System >> 2 events of voice loaded
System >> 2 events of warn loaded

**Comment by CorwinDev** [comment]
Did you try to run `kill 1` in shell?

And join our discord so we can provide faster support: discord.gg/CorwinDev
