### ISSUE TITLE
Music dont work anymore

### ISSUE THREAD

**Issue by AsnaCode** [CorwinDev/Discord-Bot#97]
Hey i wanted to hear music but this error pops up!

RangeError: No available nodes.
    at new Player (/root/AsnaBOT/node_modules/erela.js/dist/structures/Player.js:102:19)
    at Manager.create (/root/AsnaBOT/node_modules/erela.js/dist/structures/Manager.js:213:16)
    at module.exports (/root/AsnaBOT/src/commands/music/play.js:23:32)
    at Client.client.loadSubcommands (/root/AsnaBOT/src/handlers/functions/functions.js:88:130)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by AsnaCode** [comment]
![image](https://user-images.githubusercontent.com/123818929/215271629-493b38ad-727c-466b-aa04-87d44bc38e5c.png)

**Comment by CorwinDev** [comment]
Your lavalink is not available

**Comment by AsnaCode** [comment]
fr?

**Comment by UnknownX0001** [comment]
> fr?

change lavalink server (change it to some free lavalink server with no SSL)

**Comment by Blackittenz** [comment]
> change lavalink server (change it to some free lavalink server with no SSL)
how ? can you tell me pls

**Comment by UnknownX0001** [comment]
> > change lavalink server (change it to some free lavalink server with no SSL)
> 
> how ? can you tell me pls
```
Host : lava4.horizxon.studio
Port : 80
Password : "horizxon.studio"
```
put the above in .env file (or secrets tab if you are using replit) as LAVALINK_HOST, LAVALINK_PORT and LAVALINK_PASSWORD

**Comment by Blackittenz** [comment]
> > > change lavalink server (change it to some free lavalink server with no SSL)
> > 
> > 
> > how ? can you tell me pls
> 
> ```
> Host : lava4.horizxon.studio
> Port : 80
> Password : "horizxon.studio"
> ```
> 
> put the above in .env file (or secrets tab if you are using replit) as LAVALINK_HOST, LAVALINK_PORT and LAVALINK_PASSWORD

im using replit, when i put that on secret tab, i got this error
![Screenshot 2023-03-12 230613](https://user-images.githubusercontent.com/119280170/224557166-20283054-2ced-45f8-94af-36fb2a83301a.png)

**Comment by UnknownX0001** [comment]
> > > > change lavalink server (change it to some free lavalink server with no SSL)
> > > 
> > > 
> > > how ? can you tell me pls
> > 
> > 
> > ```
> > Host : lava4.horizxon.studio
> > Port : 80
> > Password : "horizxon.studio"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > put the above in .env file (or secrets tab if you are using replit) as LAVALINK_HOST, LAVALINK_PORT and LAVALINK_PASSWORD
> 
> im using replit, when i put that on secret tab, i got this error ![Screenshot 2023-03-12 230613](https://user-images.githubusercontent.com/119280170/224557166-20283054-2ced-45f8-94af-36fb2a83301a.png)

oh sorry my bad that one is not working i think
https://lavalink.darrennathanael.com/NoSSL/lavalink-without-ssl/
choose any one at random here and try

**Comment by Blackittenz** [comment]
> > > > > change lavalink server (change it to some free lavalink server with no SSL)
> > > > 
> > > > 
> > > > how ? can you tell me pls
> > > 
> > > 
> > > ```
> > > Host : lava4.horizxon.studio
> > > Port : 80
> > > Password : "horizxon.studio"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > put the above in .env file (or secrets tab if you are using replit) as LAVALINK_HOST, LAVALINK_PORT and LAVALINK_PASSWORD
> > 
> > 
> > im using replit, when i put that on secret tab, i got this error ![Screenshot 2023-03-12 230613](https://user-images.githubusercontent.com/119280170/224557166-20283054-2ced-45f8-94af-36fb2a83301a.png)
> 
> oh sorry my bad that one is not working i think https://lavalink.darrennathanael.com/NoSSL/lavalink-without-ssl/ choose any one at random here and try

thank you so much, its fixed

**Comment by tatadeew** [comment]
how to fix this?

![image](https://user-images.githubusercontent.com/86995317/229219196-8dd02a6c-077d-4134-91d3-44d1d3f0f1df.png)
